# Generated by Django 4.1.4 on 2022-12-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowd_fund", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crowdfund",
            name="description",
        ),
        migrations.RemoveField(
            model_name="crowdfund",
            name="wallet_address",
        ),
        migrations.AlterField(
            model_name="crowdfund",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
