# Generated by Django 4.1.4 on 2023-01-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowd_fund", "0002_remove_crowdfund_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crowdfund",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
